### ISSUE TITLE
cdコマンドについて

### ISSUE THREAD

**Issue by tamemoto** [kazuki-komori/portfolio-CUI#2]
<img width="401" alt="スクリーンショット 2021-01-12 1 13 13" src="https://user-images.githubusercontent.com/46603895/104206918-7a9cca00-5473-11eb-927b-382deb3d323d.png">

 `cd ..` で正常に動作するものの、エラー文でる😭(ちなみに自分は `cd ../` 派なのでこちらも対応していただけると、、)
 `cd` みたいに何もディレクトリ指定しないとホームディレクトリに戻って欲しい

**Comment by kazuki-komori** [comment]
ご丁寧にありがとうございます！！
バグっぽいですね 👀 
修正対応します 🙇

**Comment by kazuki-komori** [comment]
@tamemoto 
修正 & 追加が完了したので、issue close します 🔐
