### ISSUE TITLE
helpと引数エラー

### ISSUE THREAD

**Issue by eggplants** [kazuki-komori/portfolio-CUI#3]
![image](https://user-images.githubusercontent.com/42153744/104258762-86b07800-54c3-11eb-85d0-d6d38f6ad6a3.png)

- コマンドへの`-h, --help`
- 存在しない引数へのエラー

があると嬉しいです

**Comment by kazuki-komori** [comment]
@eggplants ご提案ありがとうございます！　順次対応させていただきます 🙇
