### ISSUE TITLE
Open (Twitter or Github or other links)

### ISSUE THREAD

**Issue by harukitosa** [kazuki-komori/portfolio-CUI#5]
すごくかっこいいポートフォリオですね！

アイデアとして一つだけ！
linksででた各種リンクに
Open Twitterとコマンドを打ち込むとそのリンクに飛ぶというのはどうでしょうか？

**Comment by kazuki-komori** [comment]
@harukitosa 
ありがとうございます！！
その発想はありませんでした！
実装します！

**Comment by tamemoto** [comment]
reactみたいに `npm run twitter`や`npm run github` とか打って、 `Open the Twitter page...` みたいな文言出力したあとリンクに飛ぶのどう??

**Comment by kazuki-komori** [comment]
@tamemoto 
かっこいい！！
npm コマンド好きなのでそちらの方法取ります！！

**Comment by kazuki-komori** [comment]
@harukitosa @tamemoto 
実装完了したので issue 閉じます！
ありがとうございました 🙇
